# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3b867d5f3d5d0d04c2f696d65ae6ca46645ea07ffc52c21bc3c15c850233d28de40ac3e24340b44c24b15a86293e1e1feb3e5ca095d694df054217bc02af6b7

test:
  secret_key_base: 3292e8f06b38012d497d2d30857511fbc77ebd83bfbec475156e663f787531b14ab1acea855857bea69f475084433a6630211a376afd9a919691714b6cedd4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
